### ISSUE TITLE
How to run this matlab program

### ISSUE THREAD

**Issue by csm-1994** [samborkent/plasma-solver#2]

**Comment by samborkent** [comment]
Hello, I just read your message. Did you manage to run the project correctly?
The main code is located in plasmaSolver.m, which should be able to run.
The alternativeSolver.m might contain some problem as it contains a prototype of a new collision calculation method I was developing, which would be faster and allow for collision calculation between plasma particles. Unfortunately, I was not able to finish it.
So, please use the plasmaSolver.m. If it throws an error, please let me know and I'll try to fix it.
More information about the prigram can be found in the report and presentation files in the documentation folder.
Let me know if there are any more questions.

**Comment by mmfadhali** [comment]
Hello
I like your code but could not run it even with plasmaSolver.m
it gives me the following error
Error using sum
Trailing string input must be 'double', 'native', 'default', 'omitnan' or 'includenan'.

Error in initialVelocityDistribution (line 86)
nParticleVeloDist = ( nParticleVeloDist ./ sum(nParticleVeloDist, 'all') ) ...

Error in plasmaSolver (line 540)
nParticleVeloInit = initialVelocityDistribution( uc,                    ...

**Comment by mmfadhali** [comment]
It is highly appreciated if you could help in putting some steps for running the code

**Comment by samborkent** [comment]
Hello. That is strange. I just cloned the repository and I fixed some problems, but I did not encounter your problem. Can you try to fetch my changes and then try to run the code again to see if you still encouter the same error?

However, something in the code is broken, as I wasn't able to reproduce the results I obtained before. I have no idea what changed, so I'll have to investigate that. Unfortunately, I do not have much time, so I that might take a while.
Please refer to the presentation file in the documentation folder to see previously obtained results.

**Comment by csm-1994** [comment]
Hello ! When I use matlab2021b to run plasmasolver.m, the following error occurs when running to 7e-6s: 

“Simulation time: 7e-06 s (Execution time: 109.1614 s)
Index exceeds the number of array elements. Index must not exceed 70.

出错 createConfigFile (第 26 行)
    'Times to plot [s]:\t\t'                    num2str( time(plotTimes) ) '\n' ...

出错 plasmaSolver (第 833 行)
    createConfigFile( currentPath, folder, fileName, commentString, ... % File settings”

How to solve this kind of error ? Thank you !

**Comment by samborkent** [comment]
Hello, it seems you are trying to plot times outside of the time axis. Try adjusting the plotTimes array. Note that this array should contain time indices, not time values.

But as mentioned in my previous comment, someting in the current state of the code is not working properly, as I was not able to reproduce the results I obtained in the past. And I don't know which changes I made that caused it.

Unfortunately, I am not working at the uni anymore so I don't really have time to maintain the code. Maybe someday I'll look into it if I find some time, but I cannot guarantee anything.

If you read the documentation you should be able to recreate a similar script. There are many improvements to the model and the code possible, so please feel welcome.

If you have any questions about the model or the code feel free to message me and I'll try to assist you if possible.
