### ISSUE TITLE
Dear Dr. Sam Borkent, I need your authorization

### ISSUE THREAD

**Issue by csm-1994** [samborkent/plasma-solver#3]
Dear Dr. Sam Borkent,

      I am a PhD student at Nanjing University of Science and Technology, China. My PhD project involves plasmas caused by pulsed laser ablation of alloy thin films. I read "Numerical modelling of the plasma plume propagation and oxidation during pulsed laser deposition of complex oxide thin films". And I carefully studied the plasma-solver program you published on github. Thank you very much for your hard work. I got some inspiration from your program, which can enrich my theoretical work. Of course, I made a lot of modifications to the program for the smooth progress of my research.
     So I would like to ask you here, can I use the modified program as part of the theoretical verification of my paper? If you can agree to my request, I will be very grateful to you! I will put your name and unit address as the second author of the paper.

Sincerely,
Shimin Chang

**Comment by samborkent** [comment]
Hello Shimin,

Thank you for taking interest in my solver and I am very happy to hear you could use it as inspiration for your research!

You have my permission to use it. The authoring offer is generous, thank you. I'm just happy that someone can still use this work to hopefully further the field.

Coincidentally, I recently gave another try at this problem to be able to better take species collisions into account. This code is still a work in progress and not public yet. It is written in Golang.

Out of curiosity, what materials are you mainly interested in in your research?

Best regards,

Sam Borkent

**Comment by csm-1994** [comment]
First of all, thank you very much for your permission, which will allow me to continue my research smoothly. And I am very interested in particle collision research and look forward to learning more from your new project.

    My research topic is the mechanism study of pulsed laser ablation of AlTi alloy film, and I am also working on programming. So using your program, I can perform microscopic analysis (from the perspective of particle collision) on the experimental results of ultra-high-speed framing camera and schlieren.

    If it is convenient for you, I would like to add you as the second author when my paper is published. Can you provide your email address and work unit?

    In addition, my email address is changshimin1994@gmail.com to facilitate subsequent communication.

Sincerely,
Shimin Chang
